#!/usr/bin/env python3
# This is an example use of PyeMenu, roughly what I use with my touchscreen pen
from pye_menu import TopMenu, SubMenuItem, ExecMenuItem
import subprocess

if __name__ == '__main__':
    subprocess.run(["@i3msg@", "--", "mark", "--add", "previous"],
                   stdout=subprocess.DEVNULL)
    try:
        TopMenu(
            ExecMenuItem("Close", ["@i3msg@", "[con_mark=previous]", "kill"]),
            ExecMenuItem("Fullscreen", ["@i3msg@", "[con_mark=previous]",
                                        "fullscreen", "toggle"]),
            ExecMenuItem("Float", ["@i3msg@", "[con_mark=previous]",
                                   "floating", "toggle"]),
            SubMenuItem("Music",
                        ExecMenuItem("⏯️", ["@mpc@", "toggle"]),
                        ExecMenuItem("1", ["@mpc@", "single"]),
                        ExecMenuItem("⏭", ["@mpc@", "next"]),
                        ExecMenuItem("⏹", ["@mpc@", "stop"]),
                        ExecMenuItem("⏮", ["@mpc@", "prev"]),
                        ExecMenuItem("🔁️", ["@mpc@", "loop"])),
            SubMenuItem("Actions",
                        SubMenuItem("Screenshot",
                                    ExecMenuItem("Screen", ["@flameshot@", "screen"]),
                                    ExecMenuItem("Full", ["@flameshot@", "full"]),
                                    ExecMenuItem("Select", ["@flameshot@", "gui"]),
                                    radius_mm=30),
                        ExecMenuItem("Lock", ["@loginctl@", "lock-session"]),
                        ExecMenuItem("Quit", ["@i3msg@", "quit"]),
                        radius_mm=30),
            radius_mm=40).main()
    finally:
        subprocess.run(["@i3msg@", "--", "unmark", "previous"],
                       stdout=subprocess.DEVNULL)
