#!/usr/bin/env python3
# This is an example use of PyeMenu, roughly what I use with my touchscreen pen
import subprocess

import i3
from pye_menu import ExecMenuItem, MenuItem, SubMenuItem, TopMenu

if __name__ == '__main__':
    i3.mark("--add", "previous")
    try:
        TopMenu(
            MenuItem("Close", action=lambda self: i3.kill(con_mark="previous")),
            MenuItem("Fullscreen", action=lambda self: i3.fullscreen("toggle", con_mark="previous")),
            MenuItem("Float", action=lambda self: i3.floating("toggle", con_mark="previous")),
            SubMenuItem("Music",
                        ExecMenuItem("⏯️", ["@mpc@", "toggle"]),
                        ExecMenuItem("1", ["@mpc@", "single"]),
                        ExecMenuItem("⏭", ["@mpc@", "next"]),
                        ExecMenuItem("⏹", ["@mpc@", "stop"]),
                        ExecMenuItem("⏮", ["@mpc@", "prev"]),
                        ExecMenuItem("🔁️", ["@mpc@", "loop"])),
            SubMenuItem("Actions",
                        SubMenuItem("Screenshot",
                                    ExecMenuItem("Screen", ["@flameshot@", "screen"]),
                                    ExecMenuItem("Full", ["@flameshot@", "full"]),
                                    ExecMenuItem("Select", ["@flameshot@", "gui"]),
                                    radius_mm=30),
                        ExecMenuItem("Lock", ["@loginctl@", "lock-session"]),
                        ExecMenuItem("Quit", ["@i3msg@", "quit"]),
                        radius_mm=30),
            radius_mm=40).main()
    finally:
        i3.unmark("previous")
        pass
